name: meson_test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-with-clang:
    runs-on: ubuntu-22.04

    env:
      CC: clang
      CXX: clang++

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install \
            libwayland-dev wayland-protocols libglm-dev libgles-dev \
            libjpeg-dev meson

      - name: Clone zwin
        uses: actions/checkout@v2
        with:
          repository: zwin-project/zwin
          path: zwin

      - name: Build zwin
        working-directory: ./zwin
        run: |
          meson build
          sudo ninja -C build install

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Build
        run: |
          meson build
          ninja -C build
        working-directory: ./main

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: zukou-test-log
          path: main/build/meson-logs/
